#!/usr/bin/env bash
# Lemonbar script
# Hakki Oktay

# Aliases
volup="pactl -- set-sink-volume 0 +10%"
voldown="pactl -- set-sink-volume 0 -10%"
mpccur="mpc -p 6645 current"
mpctog="mpc -p 6645 -q toggle"
mpcprev="mpc -p 6645 -q prev"
mpcnext="mpc -p 6645 -q next"
deskprev="bspc desktop --focus prev"
desknext="bspc desktop --focus next"

# "Modules"
Volume(){
        vol=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
        echo -ne "%{A4:$volup:}%{A5:$voldown:}\ue0e0$vol%{A}%{A}"
}

Clock(){
        DATETIME=$(date "+%a %b %d, %T")
        echo -ne "\ue266$DATETIME"
}

Temp(){
        term=$(acpi -t | awk -F '[[:space:]]+|,' '{ print $5 }')
        echo -ne "\ue01b$term"
}

Update(){
	count=$(checkupdates | wc -l)
        echo -ne "\ue0de$count"
}

Backlight(){
        bright=$(xbacklight -get)
        echo -ne "\ue14a$bright%"
}

Wireless(){

# Get the ssid name
	essid=$(wicd-cli --wireless -d|cut --complement -d" " -f1|sed -n 2p)
# Truncate to 15 characters
	if [ $(echo $essid|wc -m) -gt 15 ]; then
		essid=$(echo $essid|cut -c -15)
		essid="$essid..."
	fi
# Check if it's still connecting
	if [ -n "$(wicd-cli --wireless -i|grep "in progress")" ]; then
		essid="connecting..."
	fi
# Check if it's not connected
	if [ -z $essid ]; then
                echo -ne "\ue25c not connected"
        else
                echo -ne "\ue25c$essid"
        fi
}

Desktop(){
# Get the current desktop
	desk=$(bspc query -D -d focused --names)
# Display icon depending on the index
	case  $desk in
                0)
                        icon="\ue15f"
                        ;;
                1)
                        icon="\ue160"
                        ;;
                2)
                        icon="\ue161"
                        ;;
                3)
                        icon="\ue162"
                        ;;
                4)
                        icon="\ue163"
                        ;;
                5)
                        icon="\ue164"
                        ;;
                6)
                        icon="\ue165"
                        ;;
                7)
                        icon="\ue166"
                        ;;
                8)
                        icon="\ue167"
                        ;;
                9)
                        icon="\ue168"
                        ;;
                *)
                        icon="what did you do"
                        ;;
esac
	echo -ne "%{A:$deskprev:}\ue10b%{A}$icon%{A:$desknext:}\ue10a%{A}"
}

Window(){
# Get the window title
        wm=$(xtitle $(bspc query -N -n))
# Truncate to 52 chars
        if [ $(echo $wm | wc -m) -le 52 ]; then
                echo -ne "$wm"
        else
                wm=$(echo $wm | cut -c -52)
                echo -ne "$wm..."
        fi
}

Mpd(){
	current=$(mpc -p 6645 current)
	playing=$(mpc -p 6645 status | sed -n 2p | cut -d" " -f1)
# Check if the queue is empty
	if [ -z "$current" ]; then
		current="not playing"

	else
	# Truncate to 30 chars
		if [ $(echo $current | wc -m) -gt 30 ]; then
			current=$(echo $current | cut -c -30)
			current="$current..."
		fi
	fi
# Media control button stuff
	if [ "$playing" = "[playing]" ]; then
		toggle="\ue0e9"
	else
		toggle="\ue0e8"
	fi
	echo -ne "\ue271$current %{A:$mpcprev:}\ue0e4%{A}%{A:$mpctog:}$toggle%{A}%{A:$mpcnext:}\ue0ea%{A}"
}


# Main loop
while true; do
	   # echo "%{U#FFFFFF} %{l} $(Desktop)| $(Window) %{c} $(Mpd) %{r} $(Wireless) | $(Backlight) | $(Temp)°C | $(Volume) | $(Clock) %{U-}"
        echo "%{l} $(Desktop)| $(Window) %{c} $(Mpd) %{r} $(Wireless) | $(Backlight) | $(Volume) | $(Clock)"
        sleep 0.1
done
