#! /bin/sh

source /home/hakki/.cache/wal/colors.sh

# Init stuff --------------------------------------------------
mpd
sxhkd &
bspc monitor -d 0 1 2 3 4 5 6 7 8 9
# Looks -------------------------------------------------------
bspc config border_width        1
bspc config window_gap          15
# bspc config split_ratio          0.618
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc config bottom_padding 6
# bspc config top_padding -5
# bspc config right_padding -5
# bspc config left_padding -5

bspc config bottom_padding 105
bspc config top_padding 113
bspc config right_padding 85
bspc config left_padding 85

bspc config -d 0 right_padding -60
bspc config -d 0 left_padding -60
bspc config -d 0 bottom_padding -60
bspc config -d 0 top_padding -70

bspc config normal_border_color "$color0"
bspc config focused_border_color "$color1"
bspc config urgent_border_color "#CD2337"
bspc config presel_border_color "$color1"
# Personal settings -------------------------------------------
# Settings for libinput driver
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

# Settings for xf86-input-synaptics + synaptics-led driver
synclient VertScrollDelta=-111
synclient HorizScrollDelta=-111
synclient HorizTwoFingerScroll=1
synclient CoastingSpeed=0
synclient TapButton1=1
synclient TapButton3=2

xset s off
xset -dpms
xset s noblank
xsetroot -cursor_name left_ptr
python3 -m http.server --directory Technic/github/chanhakk.github.io/ 8181 &
# Window states------------------------------------------------
bspc rule -a Gimp state=floating follow=on
bspc rule -a St:float state=floating
bspc rule -a Gcolor3 state=floating
#bspc rule -a powermenu-electron state=fullscreen
bspc rule -a ru-turikhay-tlauncher-bootstrap-Bootstrap state=floating
bspc rule -a Unity state=floating
bspc rule -a Pavucontrol state=floating
# Startup things-----------------------------------------------
~/.local/bin/ftpstart &
~/.fehbg
#mpv --border --video-unscaled --background="#000000" --wid=0 ~/Pictures/papes/gif/1494923099708.gif --loop-file=inf --speed=1.0 &
#~/.config/bspwm/bar &
#conky -c /home/hakki/.config/conkymus/conkyrc3 &
~/.config/polybar/polybar.sh &
compton -b --config /home/hakki/.config/compton.conf &
xautolock -locker "/home/hakki/.config/i3locksimp" -time 15 -corners "00+-" -cornerredelay 20 &
